title: Puget Sound Analytics
description: Transforming data chaos into decisions that stick.
url: "https://pugetsoundanalytics.com"
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

logo: /assets/images/PSA.png
